#!/usr/bin/env python3
"""
MNIST federated training client for PQ-FL.

Trains a small CNN on a local MNIST shard then submits the flattened
weight tensor to the PQ-FL server over mTLS with AES-256-GCM payload
encryption.

Usage:
    python train.py --client-id worker-3 --round 1 --shard 0

Requires generated Python proto stubs (see README in this directory).
"""

import argparse
import hashlib
import hmac
import os
import struct
import sys

import grpc
import torch
import torch.nn as nn
import torch.nn.functional as F
from cryptography.hazmat.primitives.ciphers.aead import AESGCM
from torchvision import datasets, transforms

# Proto stubs — generated by grpc_tools.protoc, see README
sys.path.insert(0, os.path.join(os.path.dirname(__file__), "gen"))
import pqfl_pb2
import pqfl_pb2_grpc


# ---------------------------------------------------------------------------
# Model
# ---------------------------------------------------------------------------

class MnistNet(nn.Module):
    """Small CNN for MNIST. ~21k parameters."""

    def __init__(self):
        super().__init__()
        self.conv1 = nn.Conv2d(1, 8, 3, padding=1)
        self.conv2 = nn.Conv2d(8, 16, 3, padding=1)
        self.pool = nn.MaxPool2d(2)
        self.fc1 = nn.Linear(16 * 7 * 7, 64)
        self.fc2 = nn.Linear(64, 10)

    def forward(self, x):
        x = self.pool(F.relu(self.conv1(x)))
        x = self.pool(F.relu(self.conv2(x)))
        x = x.view(x.size(0), -1)
        x = F.relu(self.fc1(x))
        return self.fc2(x)


def flatten_weights(model: nn.Module) -> list[float]:
    flat = []
    for p in model.parameters():
        flat.extend(p.detach().cpu().numpy().flatten().tolist())
    return flat


def load_weights(model: nn.Module, flat: list[float]):
    offset = 0
    for p in model.parameters():
        numel = p.numel()
        chunk = torch.tensor(flat[offset : offset + numel], dtype=p.dtype)
        p.data = chunk.view(p.shape)
        offset += numel


# ---------------------------------------------------------------------------
# Crypto helpers (mirrors server/crypto_engine.cpp)
# ---------------------------------------------------------------------------

def derive_session_key(
    secret: bytes, context_parts: list[str]
) -> bytes:
    """Matches CryptoEngine::DeriveSessionKeyWithSecret."""
    to_mac = "pqfl-session-v3"
    for part in context_parts:
        to_mac += f"|{len(part)}:{part}"
    return hmac.new(secret, to_mac.encode(), hashlib.sha256).digest()


def encrypt_weights(key: bytes, plaintext: bytes) -> tuple[bytes, bytes, bytes]:
    """AES-256-GCM encrypt. Returns (ciphertext, iv, tag)."""
    iv = os.urandom(12)
    aesgcm = AESGCM(key)
    ct_with_tag = aesgcm.encrypt(iv, plaintext, None)
    ciphertext = ct_with_tag[:-16]
    tag = ct_with_tag[-16:]
    return ciphertext, iv, tag


# ---------------------------------------------------------------------------
# Training
# ---------------------------------------------------------------------------

def train_one_round(
    model: nn.Module,
    shard_index: int,
    total_shards: int = 4,
    epochs: int = 1,
    batch_size: int = 32,
    lr: float = 0.01,
):
    transform = transforms.Compose([
        transforms.ToTensor(),
        transforms.Normalize((0.1307,), (0.3081,)),
    ])
    full_dataset = datasets.MNIST(
        root="./data", train=True, download=True, transform=transform
    )

    # Shard the dataset
    n = len(full_dataset)
    shard_size = n // total_shards
    start = shard_index * shard_size
    end = start + shard_size if shard_index < total_shards - 1 else n
    subset = torch.utils.data.Subset(full_dataset, range(start, end))
    loader = torch.utils.data.DataLoader(subset, batch_size=batch_size, shuffle=True)

    optimizer = torch.optim.SGD(model.parameters(), lr=lr)
    model.train()

    total_loss = 0.0
    correct = 0
    total = 0

    for _ in range(epochs):
        for images, labels in loader:
            optimizer.zero_grad()
            output = model(images)
            loss = F.cross_entropy(output, labels)
            loss.backward()
            optimizer.step()
            total_loss += loss.item() * images.size(0)
            correct += (output.argmax(1) == labels).sum().item()
            total += images.size(0)

    avg_loss = total_loss / total if total > 0 else 0.0
    accuracy = correct / total if total > 0 else 0.0
    return len(subset), avg_loss, accuracy


# ---------------------------------------------------------------------------
# gRPC client
# ---------------------------------------------------------------------------

def build_channel(args) -> grpc.Channel:
    ca = open(os.path.join(args.certs, "ca.crt"), "rb").read()
    cert = open(os.path.join(args.certs, "client.crt"), "rb").read()
    key = open(os.path.join(args.certs, "client.key"), "rb").read()
    creds = grpc.ssl_channel_credentials(ca, key, cert)
    return grpc.secure_channel(args.address, creds)


def run(args):
    channel = build_channel(args)
    fl_stub = pqfl_pb2_grpc.FederatedLearningStub(channel)

    # 1) Register
    reg = fl_stub.RegisterClient(pqfl_pb2.ClientRegistration(
        client_id=args.client_id,
        tenant_id=args.tenant,
        model_id=args.model,
        local_dataset_size=15000,
        hardware_info="python-mnist-client",
        dataset_fingerprint=f"mnist-shard-{args.shard}",
    ))
    print(f"registered: accepted={reg.accepted} round={reg.current_round}")

    # 2) Get config
    config = fl_stub.GetTrainingConfig(pqfl_pb2.ConfigRequest(
        client_id=args.client_id,
        tenant_id=args.tenant,
        model_id=args.model,
    ))
    print(f"config: rounds={config.target_rounds} lr={config.learning_rate} "
          f"strategy={config.aggregation_strategy}")

    # 3) Train
    model = MnistNet()
    round_index = args.round
    dataset_size, loss, acc = train_one_round(
        model,
        shard_index=args.shard,
        epochs=args.epochs,
        batch_size=config.batch_size or 32,
        lr=config.learning_rate or 0.01,
    )
    print(f"trained: loss={loss:.4f} acc={acc:.4f} samples={dataset_size}")

    # 4) Encrypt weights
    secret = open(args.payload_key, "rb").read()
    nonce = f"mnist-{args.client_id}-round-{round_index}"

    # peer identity comes from the client cert CN
    peer_identity = "pqfl-edge-client"
    session_key = derive_session_key(secret, [
        peer_identity,
        args.tenant,
        args.model,
        args.client_id,
        str(round_index),
        "submit",
        nonce,
    ])

    weights = flatten_weights(model)
    plaintext = struct.pack(f"{len(weights)}f", *weights)
    ciphertext, iv, tag = encrypt_weights(session_key, plaintext)

    # 5) Submit
    resp = fl_stub.SubmitWeights(pqfl_pb2.WeightPayload(
        client_id=args.client_id,
        round_index=round_index,
        local_dataset_size=dataset_size,
        encrypted_weights=ciphertext,
        iv=iv,
        auth_tag=tag,
        tenant_id=args.tenant,
        model_id=args.model,
        base_model_version=config.active_model_version,
        client_nonce=nonce.encode(),
        job_id=config.job_id,
        assignment_id=config.assignment_id,
    ))
    print(f"submitted: accepted={resp.accepted} "
          f"clients={resp.clients_received}/{resp.clients_required} "
          f"aggregated={resp.aggregation_triggered}")
    print(f"server: {resp.message}")


def main():
    p = argparse.ArgumentParser(description="MNIST FL training client")
    p.add_argument("--address", default="localhost:50051")
    p.add_argument("--certs", default="/app/certs")
    p.add_argument("--payload-key", default="/app/data/payload.key")
    p.add_argument("--client-id", default="mnist-client-1")
    p.add_argument("--tenant", default="demo-tenant")
    p.add_argument("--model", default="demo-model")
    p.add_argument("--round", type=int, default=1)
    p.add_argument("--shard", type=int, default=0, help="MNIST shard index (0-3)")
    p.add_argument("--epochs", type=int, default=1)
    args = p.parse_args()
    run(args)


if __name__ == "__main__":
    main()
